// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrJp474ieT8OC8s7XH2XJ-uMPCd1caxlA',
    appId: '1:942534196849:web:b67598f6443707e2f665d0',
    messagingSenderId: '942534196849',
    projectId: 'litshelf-56303',
    authDomain: 'litshelf-56303.firebaseapp.com',
    storageBucket: 'litshelf-56303.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrJp474ieT8OC8s7XH2XJ-uMPCd1caxlA',
    appId: '1:942534196849:android:b67598f6443707e2f665d0',
    messagingSenderId: '942534196849',
    projectId: 'litshelf-56303',
    storageBucket: 'litshelf-56303.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrJp474ieT8OC8s7XH2XJ-uMPCd1caxlA',
    appId: '1:942534196849:ios:b67598f6443707e2f665d0',
    messagingSenderId: '942534196849',
    projectId: 'litshelf-56303',
    storageBucket: 'litshelf-56303.firebasestorage.app',
    iosBundleId: 'com.example.litshelf2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrJp474ieT8OC8s7XH2XJ-uMPCd1caxlA',
    appId: '1:942534196849:macos:b67598f6443707e2f665d0',
    messagingSenderId: '942534196849',
    projectId: 'litshelf-56303',
    storageBucket: 'litshelf-56303.firebasestorage.app',
    iosBundleId: 'com.example.litshelf2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrJp474ieT8OC8s7XH2XJ-uMPCd1caxlA',
    appId: '1:942534196849:windows:b67598f6443707e2f665d0',
    messagingSenderId: '942534196849',
    projectId: 'litshelf-56303',
    authDomain: 'litshelf-56303.firebaseapp.com',
    storageBucket: 'litshelf-56303.firebasestorage.app',
  );
}
